version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      DB_NAMESPACE: ${DB_NAMESPACE}
    volumes:
      - /shared_folder/postgresql:/var/lib/postgresql
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  db-data:
